drop table if exists public.comments cascade;

create table
  public.comments (
    id bigint generated by default as identity not null,
    task_id bigint null,
    author text null,
    text text null,
    created_at timestamp with time zone not null default timezone ('utc'::text, now()),
    user_id uuid null references public.profiles(id),
    updated_at timestamp with time zone null default current_timestamp,
    tenant_id uuid null,
    constraint comments_pkey primary key (id),
    constraint comments_task_id_fkey foreign key (task_id) references tasks (id) on delete cascade
  ) tablespace pg_default;

create index if not exists idx_comments_user_id on public.comments using btree (user_id) tablespace pg_default;

create index if not exists idx_comments_task_id on public.comments using btree (task_id) tablespace pg_default;