create table
  public.tasks (
    id bigint generated by default as identity not null,
    created_at timestamp with time zone not null default now(),
    title text null,
    status text null,
    assignee text null,
    body text not null,
    priority text null,
    due timestamp with time zone null,
    user_id uuid null,
    updated_at timestamp with time zone null default current_timestamp,
    archived boolean null default false,
    tenant_id uuid null,
    constraint tasks_pkey primary key (id),
    constraint tasks_user_id_fkey foreign key (user_id) references auth.users (id)
  ) tablespace pg_default;

create index if not exists idx_tasks_archived on public.tasks using btree (archived) tablespace pg_default;

create index if not exists idx_tasks_due on public.tasks using btree (due) tablespace pg_default;

create index if not exists idx_tasks_user_id on public.tasks using btree (user_id) tablespace pg_default;